### ISSUE TITLE
I have problems when trainning on grasping dataset after obtainning the train_file and validate_file

### ISSUE THREAD

**Issue by yuanyangman** [tnikolla/grasp-detection#17]
/robot-grasp-detection-master$ python grasp_det.py
train
distorted_inputs
True
True
pass
keep_prob = 1.0
2018-01-29 14:48:20.935569: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.1 instructions, but these are available on your machine and could speed up CPU computations.
2018-01-29 14:48:20.935592: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.2 instructions, but these are available on your machine and could speed up CPU computations.
2018-01-29 14:48:20.935613: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX instructions, but these are available on your machine and could speed up CPU computations.
2018-01-29 14:48:20.935632: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX2 instructions, but these are available on your machine and could speed up CPU computations.
2018-01-29 14:48:20.935637: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use FMA instructions, but these are available on your machine and could speed up CPU computations.
Traceback (most recent call last):
  File "grasp_det.py", line 164, in <module>
    tf.app.run(main=main, argv=[sys.argv[0]] + unparsed)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "grasp_det.py", line 117, in main
    run_training()
  File "grasp_det.py", line 113, in run_training
    coord.join(threads)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/coordinator.py", line 389, in join
    six.reraise(*self._exc_info_to_raise)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/queue_runner_impl.py", line 238, in _run
    enqueue_callable()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1063, in _single_operation_run
    target_list_as_strings, status, None)
  File "/usr/lib/python2.7/contextlib.py", line 24, in __exit__
    self.gen.next()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/errors_impl.py", line 466, in raise_exception_on_not_ok_status
    pywrap_tensorflow.TF_GetCode(status))
tensorflow.python.framework.errors_impl.FailedPreconditionError: /home/zhaojie/zhaojie/robot-grasp-detection-master
	 [[Node: ReaderReadV2 = ReaderReadV2[_device="/job:localhost/replica:0/task:0/cpu:0"](TFRecordReaderV2, input_producer)]]

**Comment by vicya** [comment]
> /robot-grasp-detection-master$ python grasp_det.py
> train
> distorted_inputs
> True
> True
> pass
> keep_prob = 1.0
> 2018-01-29 14:48:20.935569: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.1 instructions, but these are available on your machine and could speed up CPU computations.
> 2018-01-29 14:48:20.935592: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.2 instructions, but these are available on your machine and could speed up CPU computations.
> 2018-01-29 14:48:20.935613: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX instructions, but these are available on your machine and could speed up CPU computations.
> 2018-01-29 14:48:20.935632: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX2 instructions, but these are available on your machine and could speed up CPU computations.
> 2018-01-29 14:48:20.935637: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use FMA instructions, but these are available on your machine and could speed up CPU computations.
> Traceback (most recent call last):
> File "grasp_det.py", line 164, in
> tf.app.run(main=main, argv=[sys.argv[0]] + unparsed)
> File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 48, in run
> _sys.exit(main(_sys.argv[:1] + flags_passthrough))
> File "grasp_det.py", line 117, in main
> run_training()
> File "grasp_det.py", line 113, in run_training
> coord.join(threads)
> File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/coordinator.py", line 389, in join
> six.reraise(*self._exc_info_to_raise)
> File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/queue_runner_impl.py", line 238, in _run
> enqueue_callable()
> File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1063, in _single_operation_run
> target_list_as_strings, status, None)
> File "/usr/lib/python2.7/contextlib.py", line 24, in **exit**
> self.gen.next()
> File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/errors_impl.py", line 466, in raise_exception_on_not_ok_status
> pywrap_tensorflow.TF_GetCode(status))
> tensorflow.python.framework.errors_impl.FailedPreconditionError: /home/zhaojie/zhaojie/robot-grasp-detection-master
> [[Node: ReaderReadV2 = ReaderReadV2[_device="/job:localhost/replica:0/task:0/cpu:0"](TFRecordReaderV2, input_producer)]]

have you solved this problem ? I meet same
